---
title: "PH model checking"
author: "Qihang Wu"
date: "`r format(Sys.Date(), '%Y-%B-%d')`"
output: pdf_document
---

```{r setup, include = FALSE, warning = FALSE, message = FALSE}
library(survival)
library(tidyverse)
library(survminer)
library(ggfortify)
library(StepReg)

knitr::opts_chunk$set(
  warning = FALSE,
  echo = TRUE)
```


## Model checking I (graphical methods)
```{r}
# import data
dat_lung_raw <- survival::lung
dat_lung <- dat_lung_raw %>% 
  mutate_at(c(1, 3, 5, 6), .funs = ~as.factor(.)) %>% na.omit()

# --- sex ---
# km plot
fit_km_sex <- survfit(Surv(time, status == 2) ~ sex, dat_lung)
autoplot(fit_km_sex) + theme_bw() +
  labs(x = "Time (days)", y = "Survival Function",
       title = "Kaplan-Meier Survival Estimate")

# loglog vs. log time
# png("ph_checking_1.png", width = 500, height = 400)
plot(fit_km_sex, fun = "cloglog", col = c("black", "red"),
     xlab = "Time (days in log scale)", ylab = "log{-log(S(t))}",
     main = "Log of Negative Log of Estimated Survival Functions")
legend("topleft", legend = c("Male", "Female"), col = c("black", "red"), 
       lty = 1, cex = 1)

# observed vs. fitted
fit_ph_sex <- coxph(Surv(time, status == 2) ~ sex, dat_lung)

# png("ph_checking_2.png", width = 500, height = 400)
plot(fit_km_sex, col = c("blue", "darkgreen"),
     xlab = "Time (days)", ylab = "Survival Function",
     main = "Observed vs. Fitted")
lines(survfit(fit_ph_sex, newdata = data.frame(sex = as.factor(1))), # male
      col = "red", conf.int = FALSE)
lines(survfit(fit_ph_sex, newdata = data.frame(sex = as.factor(2))), # female
      col = "black", conf.int = FALSE)
legend("topright", legend = c("Observed Male", "Observed Female",
                                "Fitted Male", "Fitted Female"), 
       col = c("blue", "darkgreen", "red", "black"), lty = 1, cex = 1)
```

**Interpretation:** The above two figures demonstrate the proportional hazards assumption is hold given there is only one indicator variable `sex` in the model.

## Model checking II
```{r, fig.dim = c(10, 12)}
# --- to be updated ---
# stepwise selection
StepReg::stepwiseCox(Surv(time, status == 2) ~., dat_lung, 
                     selection = "bidirection", select = "AIC")

# interaction
fit_ph_1 <- coxph(Surv(time, status == 2) ~ sex + meal.cal + wt.loss +
                    sex * time + meal.cal * time + wt.loss * time, 
                  dat_lung)
summary(fit_ph_1)

# residual
fit_ph_2 <- coxph(Surv(time, status == 2) ~ sex + meal.cal + wt.loss, dat_lung)
test_ph <- cox.zph(fit_ph_2)
ggcoxzph(test_ph[1], ggtheme = theme_classic())
# ggsave("ph_checking_3.png", width = 6, height = 4)
ggcoxzph(test_ph[2], ggtheme = theme_classic())
# ggsave("ph_checking_4.png", width = 6, height = 4)
ggcoxzph(test_ph[3], ggtheme = theme_classic())
```


